# Generated by Django 5.2 on 2025-04-15 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_annonce_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='annonce',
            name='image',
        ),
        migrations.DeleteModel(
            name='Locataire',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
